# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'HongyiJigTechNew',
    'version': '19.0.3.30.2',
    'summary': 'Hongyijig Tech New',
    'sequence': 10,
    'description': """
Hongyijig Tech
====================
    """,
    'category': 'Hongyijig Custom New',
    'website': 'https://www.hongyijig.com/',
    'depends': ['base', 'mail', 'crm', 'contacts', 'sale_crm', 'project'],
    'data': ['security/legacy_security.xml',
             'security/security.xml',
             'security/ir.model.access.csv',
             'data/project_document_sequence.xml',
             'data/native_form_sequence.xml',
             'data/foundation_sequence.xml',
             'data/sor_sequence.xml',
             'data/bop_sequence.xml',
             'data/checklist_gate_sequence.xml',
             'data/execution_quality_sequence.xml',
             'data/commercial_bridge_sequence.xml',
             'data/knowledge_ai_sequence.xml',
             'data/crm_spine_stage_data.xml',
             'data/sseries_sequence.xml',
             'data/sseries_document_template_data.xml',
             'data/governance_master_data.xml',
             'data/programme_template_data.xml',
             'data/engineering_reference_data.xml',
             'data/hjig.inspection.checkpoint.master.csv',
             'data/native_form_template_data.xml',
             'data/checklist_template_data.xml',
             'data/ui_compatibility.xml',
             'views/crm_lead.xml',
             'views/crm_sseries_views.xml',
             'views/risk_Report_temp.xml',
             'views/email_template.xml',
             'views/project_document_views.xml',
             'views/programme_template_views.xml',
             'views/native_form_views.xml',
             'views/mould_planning_lifecycle_views.xml',
             'views/project_register_views.xml',
             'views/engineering_reference_views.xml',
             'views/foundation_views.xml',
             'views/project_planning_views.xml',
             'views/sor_views.xml',
             'views/bop_views.xml',
             'views/checklist_gate_views.xml',
             'views/execution_quality_views.xml',
             'views/commercial_bridge_views.xml',
             'views/knowledge_ai_views.xml',
             'views/governance_master_views.xml',
             'views/sseries_intake_views.xml'],
    'installable': True,
    'application': True,
    'assets': {
        'web.assets_backend': [
            'new_hongyijig_custom/static/src/scss/mould_planning.scss',
        ],
    },
    'author': 'Odoo S.A.',
    'license': 'LGPL-3',
}
