from . import test_project_document
from . import test_native_forms
from . import test_bop
from . import test_programme_template
from . import test_programme_activity_authority
from . import test_programme_architecture_authority
from . import test_programme_session
from . import test_project_registers
from . import test_foundation
from . import test_project_planning
from . import test_sor
from . import test_checklist_gate
from . import test_execution_quality
from . import test_commercial_bridge
from . import test_knowledge_ai
from . import test_ui_compatibility
from . import test_sseries_intake
from . import test_sseries_workflow
from . import test_staging_seat_guard
